services:
  api-notification:
    build:
      context: .
      dockerfile: dev.Dockerfile
    container_name: abcall-notification-local-api
    restart: always
    volumes:
      - ".:/app"
    ports:
      - "5006:3006"
    env_file:
      - .env.local
    tty: true
    links:
      - db
    depends_on:
      - db
    networks:
      - notification_net
      - app_net

      
  db:
    build:
      context: .
      dockerfile: db.Dockerfile
    env_file:
      - .env.db
    container_name: notification-local-db
    volumes:
      - "./data/postgresql:/var/lib/postgresql"
      - "./docker/postgresql:/docker-entrypoint-initdb.d"
    ports:
      - "5437:5432"
    networks:
      - notification_net




networks:
  notification_net:
    name: notification_net
    driver: bridge
  app_net:
    name: app_net
    driver: bridge